"""
Unstructured PDE Solver

Extension of the reaction-diffusion solver to work with curved and unstructured meshes
generated by CurvedMeshGenerator.

Features:
- Finite element method (FEM) for unstructured meshes
- Support for curved elements
- Integration with existing reaction-diffusion models
- Adaptive mesh refinement based on solution gradients

Author: Vivek Singh Yadav
Date: 2025-11-17
"""

import numpy as np
from typing import Callable, Optional, Tuple, List, Dict
from dataclasses import dataclass
import warnings

from curved_mesh_generator import CurvedMeshGenerator, ElementType, MeshElement
from reaction_diffusion_solver import ReactionDiffusionSystem


@dataclass
class UnstructuredPDESystem:
    """Configuration for PDE system on unstructured mesh"""
    mesh: CurvedMeshGenerator
    T: float  # Final time
    dt: float  # Time step
    Du: float  # Diffusion coefficient for u
    Dv: float = 0.0  # Diffusion coefficient for v (for coupled systems)
    boundary_condition: str = "dirichlet"  # dirichlet, neumann
    boundary_value_u: float = 0.0
    boundary_value_v: float = 0.0

    def __post_init__(self):
        """Validate configuration"""
        if self.dt <= 0 or self.T <= 0:
            raise ValueError("Time step and final time must be positive")

        if self.Du < 0 or self.Dv < 0:
            raise ValueError("Diffusion coefficients must be non-negative")

        self.num_steps = int(self.T / self.dt)
        self.t = np.linspace(0, self.T, self.num_steps + 1)


class UnstructuredPDESolver:
    """
    Finite Element solver for PDEs on unstructured meshes

    Uses P1 (linear) finite elements for spatial discretization
    and forward Euler for time integration.
    """

    def __init__(self, system: UnstructuredPDESystem):
        """
        Initialize solver

        Args:
            system: UnstructuredPDESystem configuration
        """
        self.system = system
        self.mesh = system.mesh

        # Build finite element matrices
        self._build_fem_matrices()

    def _build_fem_matrices(self) -> None:
        """Build mass and stiffness matrices for FEM"""
        n_nodes = len(self.mesh.nodes)

        # Initialize sparse matrices (using dense for simplicity)
        self.mass_matrix = np.zeros((n_nodes, n_nodes))
        self.stiffness_matrix = np.zeros((n_nodes, n_nodes))

        # Assemble element contributions
        for elem_id, elem in self.mesh.elements.items():
            if elem.element_type not in [ElementType.TRIANGLE_LINEAR,
                                        ElementType.TRIANGLE_QUADRATIC]:
                continue

            # Only use corner nodes for P1 elements
            corner_nodes = elem.node_ids[:3]

            # Get element matrices
            Me, Ke = self._element_matrices(elem)

            # Assemble into global matrices
            for i, ni in enumerate(corner_nodes):
                for j, nj in enumerate(corner_nodes):
                    self.mass_matrix[ni, nj] += Me[i, j]
                    self.stiffness_matrix[ni, nj] += Ke[i, j]

        # Identify boundary nodes
        self.boundary_nodes = [nid for nid, node in self.mesh.nodes.items()
                              if node.on_boundary]
        self.interior_nodes = [nid for nid in self.mesh.nodes.keys()
                              if nid not in self.boundary_nodes]

    def _element_matrices(self, elem: MeshElement) -> Tuple[np.ndarray, np.ndarray]:
        """
        Compute element mass and stiffness matrices for P1 triangle

        Returns:
            Me: 3x3 element mass matrix
            Ke: 3x3 element stiffness matrix
        """
        # Get corner node coordinates
        p0 = self.mesh.nodes[elem.node_ids[0]].coords()
        p1 = self.mesh.nodes[elem.node_ids[1]].coords()
        p2 = self.mesh.nodes[elem.node_ids[2]].coords()

        # Compute area using cross product
        v1 = p1 - p0
        v2 = p2 - p0
        area = 0.5 * abs(v1[0] * v2[1] - v1[1] * v2[0])

        if area < 1e-12:
            warnings.warn(f"Degenerate element {elem.id} with area {area}")
            return np.zeros((3, 3)), np.zeros((3, 3))

        # Mass matrix (using lumped mass for stability)
        # Consistent mass: Me = area/12 * [[2,1,1],[1,2,1],[1,1,2]]
        # Lumped mass (diagonal):
        Me = np.diag([area/3, area/3, area/3])

        # Stiffness matrix
        # Gradient of shape functions in reference element
        B = np.array([
            [p1[1] - p2[1], p2[1] - p0[1], p0[1] - p1[1]],
            [p2[0] - p1[0], p0[0] - p2[0], p1[0] - p0[0]]
        ]) / (2 * area)

        # Ke = area * B^T * B
        Ke = area * (B.T @ B)

        return Me, Ke

    def solve(self, u0: np.ndarray, v0: Optional[np.ndarray] = None,
             reaction_u: Optional[Callable] = None,
             reaction_v: Optional[Callable] = None,
             store_interval: int = 10) -> Tuple[np.ndarray, np.ndarray]:
        """
        Solve the PDE system

        Args:
            u0: Initial condition for u (array of size n_nodes)
            v0: Initial condition for v (for coupled systems)
            reaction_u: Reaction term function R_u(u, v, x, y)
            reaction_v: Reaction term function R_v(u, v, x, y)
            store_interval: Store solution every N time steps

        Returns:
            u_history: Solution history for u
            v_history: Solution history for v (or None)
        """
        n_nodes = len(self.mesh.nodes)
        n_steps = self.system.num_steps

        # Validate initial conditions
        if u0.shape[0] != n_nodes:
            raise ValueError(f"u0 must have {n_nodes} values")

        if v0 is not None and v0.shape[0] != n_nodes:
            raise ValueError(f"v0 must have {n_nodes} values")

        # Initialize solution arrays
        u = u0.copy()
        v = v0.copy() if v0 is not None else None

        # Storage
        n_stored = n_steps // store_interval + 1
        u_history = np.zeros((n_stored, n_nodes))
        v_history = np.zeros((n_stored, n_nodes)) if v is not None else None

        u_history[0, :] = u
        if v is not None:
            v_history[0, :] = v

        store_idx = 1

        # Time integration
        dt = self.system.dt

        # Precompute operators
        M_inv = np.linalg.inv(self.mass_matrix)
        L_u = self.system.Du * self.stiffness_matrix
        L_v = self.system.Dv * self.stiffness_matrix if v is not None else None

        print(f"Solving PDE on unstructured mesh with {n_nodes} nodes...")
        print(f"Time steps: {n_steps}, dt = {dt}")

        for step in range(1, n_steps + 1):
            t = step * dt

            # Compute diffusion terms: -M^{-1} * L * u
            diffusion_u = -M_inv @ (L_u @ u)

            if v is not None:
                diffusion_v = -M_inv @ (L_v @ v)
            else:
                diffusion_v = None

            # Compute reaction terms at nodes
            if reaction_u is not None:
                reaction_term_u = np.zeros(n_nodes)
                for nid, node in self.mesh.nodes.items():
                    v_val = v[nid] if v is not None else 0.0
                    reaction_term_u[nid] = reaction_u(u[nid], v_val, node.x, node.y)
            else:
                reaction_term_u = np.zeros(n_nodes)

            if reaction_v is not None and v is not None:
                reaction_term_v = np.zeros(n_nodes)
                for nid, node in self.mesh.nodes.items():
                    reaction_term_v[nid] = reaction_v(u[nid], v[nid], node.x, node.y)
            else:
                reaction_term_v = None

            # Forward Euler step
            u_new = u + dt * (diffusion_u + reaction_term_u)

            if v is not None and reaction_term_v is not None:
                v_new = v + dt * (diffusion_v + reaction_term_v)
            else:
                v_new = v

            # Apply boundary conditions
            if self.system.boundary_condition == "dirichlet":
                for nid in self.boundary_nodes:
                    u_new[nid] = self.system.boundary_value_u
                    if v_new is not None:
                        v_new[nid] = self.system.boundary_value_v

            elif self.system.boundary_condition == "neumann":
                # Zero-flux: already satisfied by weak form
                pass

            # Update
            u = u_new
            v = v_new

            # Store solution
            if step % store_interval == 0:
                u_history[store_idx, :] = u
                if v is not None:
                    v_history[store_idx, :] = v
                store_idx += 1

            # Progress indicator
            if step % max(1, n_steps // 10) == 0:
                print(f"  Progress: {100*step/n_steps:.1f}% (t = {t:.3f})")

        print("Solve complete!")

        return u_history, v_history

    def compute_gradient(self, u: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
        """
        Compute gradient of solution field u

        Args:
            u: Solution field at nodes

        Returns:
            grad_x, grad_y: Gradient components at nodes
        """
        n_nodes = len(self.mesh.nodes)
        grad_x = np.zeros(n_nodes)
        grad_y = np.zeros(n_nodes)
        node_count = np.zeros(n_nodes)

        # Compute gradient in each element and average to nodes
        for elem_id, elem in self.mesh.elements.items():
            if elem.element_type not in [ElementType.TRIANGLE_LINEAR,
                                        ElementType.TRIANGLE_QUADRATIC]:
                continue

            corner_nodes = elem.node_ids[:3]

            # Get coordinates
            p0 = self.mesh.nodes[corner_nodes[0]].coords()
            p1 = self.mesh.nodes[corner_nodes[1]].coords()
            p2 = self.mesh.nodes[corner_nodes[2]].coords()

            # Compute area
            v1 = p1 - p0
            v2 = p2 - p0
            area = 0.5 * abs(v1[0] * v2[1] - v1[1] * v2[0])

            if area < 1e-12:
                continue

            # Gradient of shape functions
            B = np.array([
                [p1[1] - p2[1], p2[1] - p0[1], p0[1] - p1[1]],
                [p2[0] - p1[0], p0[0] - p2[0], p1[0] - p0[0]]
            ]) / (2 * area)

            # Element gradient: grad_u = B * u_elem
            u_elem = np.array([u[nid] for nid in corner_nodes])
            grad_elem = B @ u_elem

            # Distribute to nodes
            for nid in corner_nodes:
                grad_x[nid] += grad_elem[0]
                grad_y[nid] += grad_elem[1]
                node_count[nid] += 1

        # Average
        for nid in range(n_nodes):
            if node_count[nid] > 0:
                grad_x[nid] /= node_count[nid]
                grad_y[nid] /= node_count[nid]

        return grad_x, grad_y

    def adaptive_refine(self, u: np.ndarray, threshold: float = 0.5) -> CurvedMeshGenerator:
        """
        Perform adaptive mesh refinement based on solution gradient

        Args:
            u: Current solution field
            threshold: Refinement threshold (relative to max gradient)

        Returns:
            New refined mesh generator
        """
        # Compute gradient magnitude at each element
        grad_x, grad_y = self.compute_gradient(u)
        grad_mag = np.sqrt(grad_x**2 + grad_y**2)

        # Identify elements to refine
        max_grad = grad_mag.max()
        refine_threshold = threshold * max_grad

        # For now, do uniform refinement (can be extended to adaptive)
        # This is a simplified approach
        print(f"Max gradient: {max_grad:.3e}")
        print(f"Refinement threshold: {refine_threshold:.3e}")
        print("Performing uniform refinement...")

        # Create new mesh with refinement
        new_mesh = CurvedMeshGenerator()
        new_mesh.nodes = self.mesh.nodes.copy()
        new_mesh.elements = self.mesh.elements.copy()
        new_mesh.next_node_id = self.mesh.next_node_id
        new_mesh.next_element_id = self.mesh.next_element_id

        new_mesh.refine_mesh_uniform()

        return new_mesh


def interpolate_solution_to_mesh(u_old: np.ndarray, old_mesh: CurvedMeshGenerator,
                                 new_mesh: CurvedMeshGenerator) -> np.ndarray:
    """
    Interpolate solution from old mesh to new mesh

    Args:
        u_old: Solution on old mesh
        old_mesh: Old mesh generator
        new_mesh: New mesh generator

    Returns:
        u_new: Interpolated solution on new mesh
    """
    n_new_nodes = len(new_mesh.nodes)
    u_new = np.zeros(n_new_nodes)

    # For each node in new mesh, find containing element in old mesh
    for new_nid, new_node in new_mesh.nodes.items():
        point = new_node.coords()

        # Find element containing point
        elem_id, bary_coords = find_containing_element(point, old_mesh)

        if elem_id is None:
            # Use nearest neighbor as fallback
            u_new[new_nid] = nearest_neighbor_interpolation(point, old_mesh, u_old)
        else:
            # Barycentric interpolation
            elem = old_mesh.elements[elem_id]
            corner_nodes = elem.node_ids[:3]
            u_elem = np.array([u_old[nid] for nid in corner_nodes])
            u_new[new_nid] = np.dot(bary_coords, u_elem)

    return u_new


def find_containing_element(point: np.ndarray,
                           mesh: CurvedMeshGenerator) -> Tuple[Optional[int], Optional[np.ndarray]]:
    """
    Find element containing a point and compute barycentric coordinates

    Args:
        point: Point coordinates (x, y)
        mesh: Mesh generator

    Returns:
        elem_id: Element ID (None if not found)
        bary_coords: Barycentric coordinates (None if not found)
    """
    for elem_id, elem in mesh.elements.items():
        if elem.element_type not in [ElementType.TRIANGLE_LINEAR,
                                    ElementType.TRIANGLE_QUADRATIC]:
            continue

        corner_nodes = elem.node_ids[:3]
        p0 = mesh.nodes[corner_nodes[0]].coords()
        p1 = mesh.nodes[corner_nodes[1]].coords()
        p2 = mesh.nodes[corner_nodes[2]].coords()

        # Compute barycentric coordinates
        v0 = p2 - p0
        v1 = p1 - p0
        v2 = point - p0

        dot00 = np.dot(v0, v0)
        dot01 = np.dot(v0, v1)
        dot02 = np.dot(v0, v2)
        dot11 = np.dot(v1, v1)
        dot12 = np.dot(v1, v2)

        inv_denom = 1 / (dot00 * dot11 - dot01 * dot01)
        u = (dot11 * dot02 - dot01 * dot12) * inv_denom
        v = (dot00 * dot12 - dot01 * dot02) * inv_denom

        # Check if point is in triangle
        if (u >= -1e-10) and (v >= -1e-10) and (u + v <= 1 + 1e-10):
            bary_coords = np.array([1 - u - v, v, u])
            return elem_id, bary_coords

    return None, None


def nearest_neighbor_interpolation(point: np.ndarray, mesh: CurvedMeshGenerator,
                                   u: np.ndarray) -> float:
    """Nearest neighbor interpolation as fallback"""
    min_dist = float('inf')
    nearest_value = 0.0

    for nid, node in mesh.nodes.items():
        dist = np.linalg.norm(point - node.coords())
        if dist < min_dist:
            min_dist = dist
            nearest_value = u[nid]

    return nearest_value
